### PR TITLE
GITOPS-2371: Rename tab name to Environments

### PR DESCRIPTION
**Pull request by ciiay**
This PR is for [GITOPS-2371](https://issues.redhat.com/browse/GITOPS-2371).

### CODE REVIEW

**Review by keithchong — CHANGES_REQUESTED** [review]
Should we use the externalized string?

**Comment by keithchong** [comment]
@ciiay or @wtam2018 , could you add the rule to require approvals before a pull request can be merged? I can't seem to do this. (I did add it to the common library repo though)

**Comment by ciiay** [comment]
> Should we use the externalized string?

@keithchong Sorry I didn't get your question. Could you elaborate it?

**Comment by keithchong** [comment]
> > Should we use the externalized string?
> 
> @keithchong Sorry I didn't get your question. Could you elaborate it?

Hi @ciiay , check the static plugin's console-extension.json file:

"name": "%gitops-plugin~Environments%",

**Review by keithchong — APPROVED** [review]
LGTM

**Pull request merged**
